---

- name: Apache2 | Install required packages
  apt: pkg=apache2 state=installed
  tags: apache2

- name: Apache2 | Enable Rewrite Module
  command: a2enmod rewrite
  tags: apache2
  notify: Restart apache

- name: Apache2 | Remove default configuration
  file: state=absent path=/etc/apache2/sites-enabled/000-default
  notify: Restart apache
