#!/usr/bin/env python
import os
import sys


CONFIGURATION_MODULE = "settings"


def in_django_project(some_path):
    joined = os.path.join(some_path, CONFIGURATION_MODULE)
    return os.path.exists(joined + '.py') or os.path.isdir(joined) and \
                os.path.exists(os.path.join(joined, '__init__.py'))


def find_project_dir(path=os.getcwd()):
    # original_path = path
    path_split = os.path.split(path)
    while path_split[1]:
        if in_django_project(path):
            return path
        path = path_split[0]
        path_split = os.path.split(path)
    # we ran out of parents
    return None
    # return original_path


project_dir = find_project_dir(os.getcwd())
if project_dir and project_dir not in sys.path:
    sys.path.insert(0, project_dir)


if __name__ == "__main__":
    from django.core.management import execute_from_command_line

    execute_from_command_line(sys.argv)
