#!/bin/bash
currentpath=`pwd | egrep .dotfiles$`
if [ -z $currentpath ]; then
    echo "not in the right path, please cd to your .dotfiles directory"
    exit 1
fi

for f in $( ls -1Ap | egrep ^\\..*[^\/]$ ); do
    if   [ -L ~/$f ]; then
        echo ".remove existing symlink"
        rm ~/$f
    elif [ -f ~/$f ]; then
        echo ".backing up existing file ~/$f"
        mv ~/$f ~/$f.old
    fi
    echo "..Creating ~/$f"
    ln -s .dotfiles/$f ~/$f
    if [ $? -ne 0 ]; then
        echo "...oops!"
        exit 1
    fi
done
