#!/bin/bash
currentpath=`pwd | egrep .dotfiles$`
if [ -z $currentpath ]; then
    echo "not in the right path, please cd to your .dotfiles directory"
    exit 1
fi

# link dotfiles
for f in $( ls -1Ap | egrep ^\\..*[^\/]$ ); do
    if   [ -L ~/$f ]; then
        echo ".remove existing symlink"
        rm ~/$f
    elif [ -f ~/$f ]; then
        echo ".backing up existing file ~/$f"
        mv ~/$f ~/$f.old
    fi
    echo "..Creating ~/$f"
    ln -s .dotfiles/$f ~/$f
    if [ $? -ne 0 ]; then
        echo "...oops!"
        exit 1
    fi
done

# link gnome terminal config
if [ -d ~/.gconf/apps/gnome-terminal ]; then
    rm -rf ~/.gconf/apps/gnome-terminal
elif [ -L ~/.gconf/apps/gnome-terminal ]; then
    rm ~/.gconf/apps/gnome-terminal
fi
echo ".. Linking gnome terminal settings"
ln -s ~/.dotfiles/gnome-terminal ~/.gconf/apps/gnome-terminal

# link .vim
if [ -L ~/.vim ]; then
    rm ~/.vim
fi
ln -s .dotfiles/.vim ~/.vim


# personal ~/bin
echo "* install ~/bin"
cd
mkdir -p bin
cd bin
for f in $currentpath/bin/*; do
    ln -s $f
done
