---

- name: Spotify | Add key
  apt_key: keyserver=keyserver.ubuntu.com id=94558F59

- name: Spotify | Add repository
  apt_repository: repo='deb http://repository.spotify.com stable non-free' state=present update_cache=yes

- name: Spotify | Install spotify
  apt: name=spotify-client state=latest

- name: Htop | Install htop
  apt: name=htop state=latest

- name: Wine | Add repository
  apt_repository: repo='ppa:ubuntu-wine/ppa' state=present update_cache=yes

- name: Wine | Install wine
  apt: name=wine state=latest

- name: sshfs | Install sshfs
  apt: name=sshfs state=latest

- name: sshfs | Load sshfs to kernal
  command: modprobe fuse
