---

- name: Clone dotfile repo
  sudo: false
  git: repo=https://github.com/patrickocoffeyo/dotfiles.git dest=/home/{{ ansible_ssh_user }}/.dotfiles update=yes recursive=yes

- name: Vim | Install vim
  apt: pkg=vim state=installed

- name: Vim | Remove default .vim directory
  file: path=/home/{{ ansible_ssh_user }}/.vim state=absent

- name: Vim | Copy .vim directory
  file: path=/home/{{ ansible_ssh_user }}/.vim src=/home/{{ ansible_ssh_user }}/.dotfiles/.vim state=link owner={{ ansible_ssh_user }}

- name: Vim | Symlink .vimrc
  file: path=/home/{{ ansible_ssh_user }}/.vimrc src=/home/{{ ansible_ssh_user }}/.dotfiles/.vimrc state=link owner={{ ansible_ssh_user }}

- name: ZSH | Install ZSH
  apt: pkg=zsh state=installed

- name: ZSH | Clone oh-my-zsh repo
  sudo: false
  git: repo=https://github.com/robbyrussell/oh-my-zsh.git dest=/home/{{ ansible_ssh_user }}/.oh-my-zsh

- name: ZSH | Remove default .zshrc
  file: path=/home/{{ ansible_ssh_user }}/.zshrc state=absent

- name: ZSH | Symlink .zshrc
  file: path=/home/{{ ansible_ssh_user }}/.zshrc src=/home/{{ ansible_ssh_user }}/.dotfiles/.zshrc state=link owner={{ ansible_ssh_user }}

- name: ZSH | Set ZSH as the default shell
  user: name={{ ansible_ssh_user }} shell=/usr/bin/zsh

- name: Terminal | Make Terminal has pretty colors
  command: bash /home/{{ ansible_ssh_user }}/.dotfiles/gnome-terminal-theme.sh
