---

- name: Ruby | Install latest version of ruby
  apt: pkg={{ item }} state=latest
  with_items:
    - ruby2.0
    - ruby2.0-dev

- name: Ruby | Symlink ruby
  file: src=/usr/bin/ruby2.0 dest=/usr/local/bin/ruby state=link

- name: Ruby | Symlink ruby gems
  file: src=/usr/bin/gem2.0 dest=/usr/local/bin/gem state=link
