---
# List handlers for Apache2

- name: Stop apache
  service: name=apache2 state=stop

- name: Start apache
  service: name=apache2 state=start

- name: Restart apache
  service: name=apache2 state=restarted

- name: Reload apache
  service: name=apache2 state=reload

- name: Graceful apache
  service: name=apache2 state=graceful
