- name: Node.js
  apt: name=nodejs state=installed
  apt: name=npm state=installed

- name: For some fucking reason this needs to be separate
  apt: name=nodejs-legacy state=installed

- npm: name=n global=yes

- file: path=/usr/local owner={{ ansible_ssh_user }} recurse=yes

- shell: n --stable

- npm: name=grunt=cli global=yes
  npm: name=jshint global=yes
