#!/bin/bash
# This hook is run after this virtualenv is activated.

export IPYTHONDIR=$VIRTUAL_ENV/.ipython
alias vivirtualenv="$VISUAL $VIRTUAL_ENV/bin/postdeactivate $VIRTUAL_ENV/bin/postactivate"

# change my title, alias in my .crcrc
tit $(basename $VIRTUAL_ENV)

# Activate autoenv by manually triggering its cd override
cd $PWD
