---

- name: Redis | Install python-software-properties
  apt: name=python-software-properties state=latest

- name: Redis | Add repository
  apt_repository: repo='ppa:rwky/redis' state=present update_cache=yes

- name: Redis | Install redis
  apt: name=redis-server state=latest
