---

- name: PHP5 | Install php, and other needed packages.
  action: apt pkg={{ item }} state=installed
  with_items:
    - php5
    - php5-dev
    - php-pear
    - php5-intl
    - php5-ldap
    - php5-curl
    - php5-cli
    - php5-xdebug
    - php5-mysql
    - php5-json
  notify: Restart apache

- name: PHP5 | Update pear channels
  command: pear update-channels

- name: PHP5 | Update pear packages
  command: pear upgrade-all

- name: PHP5 | Set pear auto-discover
  command: pear config-set auto_discover 1

- name: Curl | Install Curl
  apt: name=curl state=installed

- name: Composer | install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer.phar

- name: Composer | composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: Composer | composer executable
  shell: chmod a+x /usr/local/bin/composer

- name: PHP5 | Configuration /var/www/html/index.php
  template: src=var-www-html-index.php dest=/var/www/html/index.php mode=0644

- name: PHP5 | Remove index.html
  file: state=absent path=/var/www/html/index.html

- name: PHP5 | Configuration /etc/php5/apache2/php.ini
  template: src=etc-php5-apache2-php.ini dest=/etc/php5/apache2/php.ini mode=0644
  notify: Restart apache
