---

- name: HipChat | Add key
  apt_key: url=https://www.hipchat.com/keys/hipchat-linux.key state=present

- name: HipChat | Add repository
  apt_repository: repo='deb http://downloads.hipchat.com/linux/apt stable main' state=present

- name: HipChat | Install HipChat
  apt: name=hipchat update_cache=yes state=latest
